import GapFamily.Analytic.Cusp.Profile.CuspProfileCore
import GapFamily.Analytic.Cusp.Fourier.CuspAverageTrace
import Mathlib.Topology.Algebra.Module.Basic

/-!
# The actual closed scalar cusp form subspace

The generating set consists of the genuine modular core forms obtained from
globally smooth compact profiles supported strictly above height one. Taking
its complex span and closure is performed inside the actual completed modular
form domain, with its mass-plus-gradient norm.
-/

noncomputable section

namespace GapFamily.Analytic

open Set Filter ModularGradient
open scoped Topology ContDiff

/-- Literal compact scalar profile forms, before linear span or completion. -/
def cuspScalarFormGenerators : Set FormDomain :=
  {u | ∃ (b : ℝ → ℂ) (hb : ContDiff ℝ ∞ b) (hc : HasCompactSupport b)
      (hs : tsupport b ⊆ Ioi (1 : ℝ)), u = coreForm (cuspProfileCore b hb hc hs)}

/-- The closed complex form subspace generated by actual compact scalar cusp profiles. -/
def cuspScalarForm : Submodule ℂ FormDomain :=
  (Submodule.span ℂ cuspScalarFormGenerators).topologicalClosure

instance cuspScalarForm_normedSpace : NormedSpace ℂ cuspScalarForm :=
  Submodule.normedSpace cuspScalarForm

instance cuspScalarForm_innerProductSpace : InnerProductSpace ℂ cuspScalarForm :=
  Submodule.innerProductSpace (𝕜 := ℂ) (E := FormDomain) cuspScalarForm

theorem cuspScalarForm_isClosed : IsClosed (cuspScalarForm : Set FormDomain) :=
  (Submodule.span ℂ cuspScalarFormGenerators).isClosed_topologicalClosure

instance cuspScalarForm_completeSpace : CompleteSpace cuspScalarForm :=
  cuspScalarForm_isClosed.completeSpace_coe

theorem cuspProfileCore_mem_cuspScalarForm (b : ℝ → ℂ) (hb : ContDiff ℝ ∞ b)
    (hc : HasCompactSupport b) (hs : tsupport b ⊆ Ioi (1 : ℝ)) :
    coreForm (cuspProfileCore b hb hc hs) ∈ cuspScalarForm :=
  (Submodule.span ℂ cuspScalarFormGenerators).le_topologicalClosure
    (Submodule.subset_span ⟨b, hb, hc, hs, rfl⟩)

/-- Closed linear properties of all genuine profile generators pass to the
actual completed scalar form space. -/
theorem cuspScalarForm_le_of_isClosed (p : Submodule ℂ FormDomain)
    (hp : IsClosed (p : Set FormDomain))
    (hgen : ∀ (b : ℝ → ℂ) (hb : ContDiff ℝ ∞ b) (hc : HasCompactSupport b)
      (hs : tsupport b ⊆ Ioi (1 : ℝ)), coreForm (cuspProfileCore b hb hc hs) ∈ p) :
    cuspScalarForm ≤ p := by
  apply (Submodule.span ℂ cuspScalarFormGenerators).topologicalClosure_minimal _ hp
  apply Submodule.span_le.mpr
  rintro u ⟨b, hb, hc, hs, rfl⟩
  exact hgen b hb hc hs

/-- Limits in the actual form norm stay in the scalar form subspace. -/
theorem cuspScalarForm_mem_of_tendsto {ι : Type*} {l : Filter ι} [NeBot l]
    {f : ι → FormDomain} {u : FormDomain}
    (hf : ∀ᶠ i in l, f i ∈ cuspScalarForm) (hu : Tendsto f l (𝓝 u)) :
    u ∈ cuspScalarForm :=
  cuspScalarForm_isClosed.mem_of_tendsto hu hf

/-- In particular, an actual form limit of compact scalar profiles belongs to
the closed scalar form subspace. -/
theorem cuspScalarForm_mem_of_profile_tendsto (b : ℕ → ℝ → ℂ)
    (hb : ∀ n, ContDiff ℝ ∞ (b n)) (hc : ∀ n, HasCompactSupport (b n))
    (hs : ∀ n, tsupport (b n) ⊆ Ioi (1 : ℝ)) {u : FormDomain}
    (hu : Tendsto (fun n => coreForm (cuspProfileCore (b n) (hb n) (hc n) (hs n)))
      atTop (𝓝 u)) : u ∈ cuspScalarForm :=
  cuspScalarForm_mem_of_tendsto
    (Eventually.of_forall fun n => cuspProfileCore_mem_cuspScalarForm (b n) (hb n) (hc n) (hs n)) hu

/-- The genuine ambient value map on the completed scalar form space. -/
def scalarCuspEmbedding : cuspScalarForm →L[ℂ] ModularHilbert :=
  formEmbedding.comp cuspScalarForm.subtypeL

theorem scalarCuspEmbedding_apply (u : cuspScalarForm) :
    scalarCuspEmbedding u = formEmbedding (u : FormDomain) := rfl

theorem scalarCuspEmbedding_injective : Function.Injective scalarCuspEmbedding :=
  formEmbedding_injective.comp Subtype.val_injective

end GapFamily.Analytic
